version: '3.6'
services:
    example:
        image: ondrejsika/go-hello-world:2
        networks:
             - traefik
        labels:
            - traefik.frontend.rule=Host:hello.$SUFFIX
            - traefik.enable=true

networks:
    traefik:
        external:
            name: traefik
